package com.example.covidtrackingapp

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

// entity represents SQLite table (so risk_table)
@Entity(tableName = "risk_table")
// primary key is id each entry is number by that's autogenerated
class Risk(@PrimaryKey(autoGenerate = true) val id:Int,
           @ColumnInfo(name="location") val location:String,
           @ColumnInfo(name="location_state") val location_state:String,
           @ColumnInfo(name="number_people") val number_people:String,
           @ColumnInfo(name="duration") val duration:String,
           @ColumnInfo(name="masks") val masks:String,
           @ColumnInfo(name="vaccinated") val vaccinated:String,
           @ColumnInfo(name="locationRatio") val locationRatio:String,
           @ColumnInfo(name="cases") val cases:String,
           @ColumnInfo(name="vacCompleted") val vacCompleted:String)
          // @ColumnInfo generates a new column in database
          // some of these are not visible to the user
          // can see everything inside the database under the Database Inspector when the emulator is actively running